# Generated by Django 5.1.5 on 2025-03-10 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_modelformsetmodel_alter_rubric_name_goiteen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('stuff_id', models.AutoField(primary_key=True, serialize=False)),
                ('stuff_name', models.CharField(max_length=100)),
                ('stuff_desc', models.TextField()),
                ('photo', models.ImageField(upload_to='stuff_photos/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
