# Generated by Django 5.1.5 on 2025-03-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_stuff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stuff',
        ),
    ]
